version: "3"

services:
    nominatim:
        container_name: nominatim
        image: mediagis/nominatim:4.2
        restart: always
        ports:
            - "8080:8080"
        environment:
            # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
            PBF_URL: https://download.geofabrik.de/north-america/us-latest.osm.pbf
            REPLICATION_URL: https://download.geofabrik.de/north-america/us-updates
            NOMINATIM_PASSWORD: 8v!T_nBfi@Bt-YjkKEfYbe.48o8v!wubmo4wRrHWz3znt74VRw9iVwoMrojL3EnY
            IMPORT_STYLE: full
            REPLICATION_UPDATE_INTERVAL: 86400
            REPLICATION_RECHECK_INTERVAL: 2400
            UPDATE_MODE: catch-up
            IMPORT_US_POSTCODES: true
            IMPORT_TIGER_ADDRESSES: true

        volumes:
            - nominatim-data:/var/lib/postgresql/14/main
        shm_size: 2gb

volumes:
    nominatim-data:
